//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdlinSoftware.BlackJack.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdlinSoftware.BlackJack.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet 10.
        /// </summary>
        public static string Bet10ButtonText {
            get {
                return ResourceManager.GetString("Bet10ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet 20.
        /// </summary>
        public static string Bet20ButtonText {
            get {
                return ResourceManager.GetString("Bet20ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet 50.
        /// </summary>
        public static string Bet50ButtonText {
            get {
                return ResourceManager.GetString("Bet50ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet 5.
        /// </summary>
        public static string Bet5ButtonText {
            get {
                return ResourceManager.GetString("Bet5ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet All.
        /// </summary>
        public static string BetAllButtonText {
            get {
                return ResourceManager.GetString("BetAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack!.
        /// </summary>
        public static string BlackJack {
            get {
                return ResourceManager.GetString("BlackJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current bet: {0}.
        /// </summary>
        public static string CurrentBet {
            get {
                return ResourceManager.GetString("CurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer has won.
        /// </summary>
        public static string DealerHasWon {
            get {
                return ResourceManager.GetString("DealerHasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer&apos;s hand:.
        /// </summary>
        public static string DealersHand {
            get {
                return ResourceManager.GetString("DealersHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer&apos;s Money: {0}.
        /// </summary>
        public static string DealersMoney {
            get {
                return ResourceManager.GetString("DealersMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer went bust.
        /// </summary>
        public static string DealerWentBust {
            get {
                return ResourceManager.GetString("DealerWentBust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is over. Dealer won.
        /// </summary>
        public static string DealerWonGame {
            get {
                return ResourceManager.GetString("DealerWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string HitButtonText {
            get {
                return ResourceManager.GetString("HitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New game.
        /// </summary>
        public static string MenuNewGame {
            get {
                return ResourceManager.GetString("MenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string NewGameButtonText {
            get {
                return ResourceManager.GetString("NewGameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player has won.
        /// </summary>
        public static string PlayerHasWon {
            get {
                return ResourceManager.GetString("PlayerHasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s hand:.
        /// </summary>
        public static string PlayersHand {
            get {
                return ResourceManager.GetString("PlayersHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Money: {0}.
        /// </summary>
        public static string PlayersMoney {
            get {
                return ResourceManager.GetString("PlayersMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player went bust.
        /// </summary>
        public static string PlayerWentBust {
            get {
                return ResourceManager.GetString("PlayerWentBust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is over. Player won.
        /// </summary>
        public static string PlayerWonGame {
            get {
                return ResourceManager.GetString("PlayerWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active back:.
        /// </summary>
        public static string SettingsActiveBack {
            get {
                return ResourceManager.GetString("SettingsActiveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active deck:.
        /// </summary>
        public static string SettingsActiveDeck {
            get {
                return ResourceManager.GetString("SettingsActiveDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial dealer&apos;s money:.
        /// </summary>
        public static string SettingsInitialDealerMoney {
            get {
                return ResourceManager.GetString("SettingsInitialDealerMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial player&apos;s money:.
        /// </summary>
        public static string SettingsInitialPlayerMoney {
            get {
                return ResourceManager.GetString("SettingsInitialPlayerMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand.
        /// </summary>
        public static string StandButtonText {
            get {
                return ResourceManager.GetString("StandButtonText", resourceCulture);
            }
        }
    }
}
